background {
    monitor =
	color = rgba(25, 20, 20, 1.0)
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    placeholder_text =

    outer_color = rgb(ffffff)
    check_color = rgb(0, 255, 0)
    fail_color = rgb(255, 0, 0)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
